<?php

namespace AppBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSessionsAbsentByStudentAndQuarter($student, $quarter)
    {
        // TODO CG
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.date BETWEEN :start AND :end')
            ->setParameter('start', $quarter->getStartDate())
            ->setParameter('end', $quarter->getEndDate())
            ->andWhere('a.student = :student')
            ->setParameter('student', $student);

        return $qb->getQuery()->getResult();
    }
}
