<?php

namespace AppBundle\Repository;

/**
 * Interventionepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastIntervention()
    {
        $qb = $this->createQueryBuilder('i')
            ->select('MAX(i.interventionDate)');

        return $qb->getQuery()->getOneOrNullResult();
    }
}
