<?php

namespace AppBundle\Repository;

/**
 * SanctionReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
