<?php

namespace AppBundle\Repository;

/**
 * SanctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSanctionsAlertsByClass($classId)
    {
        $qb = $this->createQueryBuilder('sa')
            ->select('sa', 'st', 'c')
            ->join('sa.student', 'st')
            ->join('st.class', 'c')
            ->where('sa.done = 0')
            ->andWhere('c.id = :classId')
            ->setParameter('classId', $classId);

        return $qb->getQuery()->getResult();
    }

}
