<?php

namespace AppBundle\Repository;

/**
 * SkillStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillStudentRepository extends \Doctrine\ORM\EntityRepository
{
}
